# Generated by Django 5.0.9 on 2026-09-23 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alternative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("position", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("weight", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "direction",
                    models.CharField(
                        choices=[("benefit", "Benefit"), ("cost", "Cost")], max_length=8
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlternativeScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.DecimalField(decimal_places=3, max_digits=6)),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "alternative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="decisions.alternative",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="decisions.criterion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("context", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCORED", "Scored"),
                            ("COMMITTED", "Committed"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("REVIEWED", "Reviewed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="criterion",
            name="decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="decisions.decision",
            ),
        ),
        migrations.AddField(
            model_name="alternative",
            name="decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternatives",
                to="decisions.decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="alternativescore",
            constraint=models.UniqueConstraint(
                fields=("alternative", "criterion"), name="unique_score_cell"
            ),
        ),
        migrations.AddConstraint(
            model_name="alternativescore",
            constraint=models.CheckConstraint(
                check=models.Q(("score__gte", 1), ("score__lte", 10)),
                name="score_within_configured_range",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(fields=["owner", "status"], name="decisions_d_owner_i_60277d_idx"),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["owner", "-updated_at"], name="decisions_d_owner_i_70b337_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="criterion",
            index=models.Index(
                fields=["decision", "is_active"], name="decisions_c_decisio_3a0642_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.UniqueConstraint(
                fields=("decision", "name"), name="unique_criterion_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.CheckConstraint(
                check=models.Q(("weight__gt", 0)), name="criterion_weight_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="alternative",
            index=models.Index(
                fields=["decision", "position"], name="decisions_a_decisio_e59a21_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alternative",
            constraint=models.UniqueConstraint(
                fields=("decision", "name"), name="unique_alternative_name"
            ),
        ),
    ]
