"""baseline: adopt existing Django-created schema

Revision ID: b155269d9f5d
Revises: 
Create Date: 2026-09-23 12:40:53.155962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b155269d9f5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_user',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts_user')),
    sa.UniqueConstraint('email', name=op.f('uq_accounts_user_email'))
    )
    op.create_index('unique_lower_email', 'accounts_user', [sa.text('lower(email)')], unique=True)
    op.create_table('accounts_userprofile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('quota_tier', sa.String(length=32), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], name=op.f('fk_accounts_userprofile_user_id_accounts_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts_userprofile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_accounts_userprofile_user_id'))
    )
    op.create_table('decisions_decision',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    # NOTE: no status CHECK constraint here on purpose — Django never created one (verified live);
    # added in the next revision so `alembic stamp` on an existing DB stays accurate (see ADR).
    sa.ForeignKeyConstraint(['owner_id'], ['accounts_user.id'], name=op.f('fk_decisions_decision_owner_id_accounts_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions_decision'))
    )
    op.create_index('decisions_d_owner_i_60277d_idx', 'decisions_decision', ['owner_id', 'status'], unique=False)
    op.create_index('decisions_d_owner_i_70b337_idx', 'decisions_decision', ['owner_id', 'updated_at'], unique=False)
    # NOTE: refresh_tokens is NOT created here even though it was autogenerated into this revision
    # originally — it's a genuinely NEW table (Django never had it), so bundling its creation into
    # the "baseline" revision would make it silently skipped on an existing-DB adoption (which
    # `alembic stamp`s this revision rather than running its DDL). Moved to its own revision.
    op.create_table('decisions_alternative',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions_decision.id'], name=op.f('fk_decisions_alternative_decision_id_decisions_decision'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions_alternative')),
    sa.UniqueConstraint('decision_id', 'name', name='unique_alternative_name')
    )
    op.create_index('decisions_a_decisio_e59a21_idx', 'decisions_alternative', ['decision_id', 'position'], unique=False)
    op.create_table('decisions_criterion',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    # NOTE: no direction CHECK constraint here on purpose — see the status note above; both are
    # added together in the next revision.
    sa.CheckConstraint('weight > 0', name='criterion_weight_positive'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions_decision.id'], name=op.f('fk_decisions_criterion_decision_id_decisions_decision'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions_criterion')),
    sa.UniqueConstraint('decision_id', 'name', name='unique_criterion_name')
    )
    op.create_index('decisions_c_decisio_3a0642_idx', 'decisions_criterion', ['decision_id', 'is_active'], unique=False)
    op.create_table('decisions_alternativescore',
    sa.Column('alternative_id', sa.UUID(), nullable=False),
    sa.Column('criterion_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 10', name='score_within_configured_range'),
    sa.ForeignKeyConstraint(['alternative_id'], ['decisions_alternative.id'], name=op.f('fk_decisions_alternativescore_alternative_id_decisions_alternative'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criterion_id'], ['decisions_criterion.id'], name=op.f('fk_decisions_alternativescore_criterion_id_decisions_criterion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions_alternativescore')),
    sa.UniqueConstraint('alternative_id', 'criterion_id', name='unique_score_cell')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions_alternativescore')
    op.drop_index('decisions_c_decisio_3a0642_idx', table_name='decisions_criterion')
    op.drop_table('decisions_criterion')
    op.drop_index('decisions_a_decisio_e59a21_idx', table_name='decisions_alternative')
    op.drop_table('decisions_alternative')
    op.drop_index('decisions_d_owner_i_70b337_idx', table_name='decisions_decision')
    op.drop_index('decisions_d_owner_i_60277d_idx', table_name='decisions_decision')
    op.drop_table('decisions_decision')
    op.drop_table('accounts_userprofile')
    op.drop_index('unique_lower_email', table_name='accounts_user')
    op.drop_table('accounts_user')
    # ### end Alembic commands ###
